### ISSUE TITLE
Add the ability to append custom attributes and load relationships on models 

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table-laravel-api#1]
I'd like to propose the idea of a `manipulator` method on `DataTableResponder`. This would allow the manipulation of the collection of results from the query.

It would be open ended to allow any manipulation to take place, for example appending custom attributes or loading relationships. This would be more useful than having separate `append` and `load` methods (although it would be nice to have these options too).

Here's an example syntax.

```php
/**
 * @param Request $request
 * @return \Illuminate\Http\JsonResponse
 */
public function dataTable(Request $request)
{
    return (new DataTableResponder(Pallet::class, $request))
        ->query(function ($query) use ($request) {
            // ... optional
        })
        ->manipulator(function ($collection) use ($request) {
            // ... make changes to the collection
        })
        ->setPerPage(10)
        ->respond();
}
```

Thoughts?

**Comment by Jord-JD** [comment]
Definitely a good idea, though I'd suggest maybe calling it `setCollectionManipulator` to be a little clearer.

**Comment by dextermb** [comment]
> Definitely a good idea, though I'd suggest maybe calling it `setCollectionManipulator` to be a little clearer.

Can do, to follow the naming convention of `setPerPage`. But I think `manipulator` would be more inline with having a callable, to make `query`. If it were _a static type_ such as: `string`, `array`, `integer` then I would agree more with `set*`.

**Comment by Jord-JD** [comment]
Let's go with `collectionManipulator`.

**Comment by dextermb** [comment]
> Let's go with `collectionManipulator`.

As it looks like _you're using the callable_, I think that `set` would _wrong_ here. Where as if you were passing a manipulator then you could use `setCollectionManipulator`:

```php
/**
 * @param Request $request
 * @return \Illuminate\Http\JsonResponse
 */
public function dataTable(Request $request)
{
    return (new DataTableResponder(Pallet::class, $request))
        ->query(function ($query) use ($request) {
            // ... optional
        })
        ->setCollectionManipulator(PalletManipulator::class)
        ->setPerPage(10)
        ->respond();
}
```
